<?php

namespace Zymfonix\Modulus;

use Illuminate\Support\Collection;

class Modulus extends Collection
{
    public function register($id, $namespace, $directory): Module
    {
        $module = new Module(
            $id,
            $namespace,
            $directory
        );

        $this->put($id, $module);

        return $module;
    }

    public function get($key, $default = null)
    {
        if (! parent::get($key)) {
            throw new \Exception("Module '$key' not registered.");
        }

        return parent::get($key, $default); // TODO: Change the autogenerated stub
    }

    public function current()
    {

    }
}
